import 'package:medlink/utils/app_imports.dart';

class Words extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "currency": "\$",
          //splash screen
          "splash_title": "Health Care is a\ntouch away",
          "login": "Log In",
          "sign_up": "Create an Account",
          "or": "or continue with",

          //login screen
          "welcome_back": "Welcome back!",
          "login_label": "Email",
          "login_hint": "Type",
          "forgot_password": "Forgot Password?",
          "login_btn": "Log In",
          "login_error_not_exist": "Account does not exist",
          "login_error_not_correct": "Oops! Email/Phone number or password is not correct",
          "login_error_suspended": "Your account has been suspended",
          "login_error_not_approved": "Your account is waiting for approval",

          //telephone screen
          "enter_phone_number": "Enter your phone number",
          "phone_number": "Phone number",
          "info": "Don't worry. We won't text you or call you. We'll send you a 4-digit code to confirm your account.",

          //verify screen
          "verify_title": "Enter the 4-digit code we sent to",
          "resend_code": "Resend code",
          "resend_code_after": "Resend code after",
          "wrong": "Wrong code",
          "verify_btn": "Verify",

          //user type screen
          "user_type_title": "Welcome to",
          "user_type_subtitle": "What are you\nlooking for?",
          "user_type_doctor_title": "Provide help",
          "user_type_doctor_subtitle": "I'm a healthcare provider",
          "user_type_patient_title": "Need help",
          "user_type_patient_subtitle": "I'm a patient member",

          //create account screen
          "emailExist": "Email already exists!",
          "create_account_title": "Create your account",
          "agree_terms": "By registering, you agree to our ",
          "terms": "Terms & Conditions \n",
          "privacy": "Privacy Policy",
          "identity_title": "Who are you ?",
          "doctor": "Doctor",
          "pharmacy": "Pharmacy",
          "hospital": "Hospital",
          "ambulance": "Ambulance",
          "license_title": "Upload license and doctorate",
          "license_description": "Please verify your credentials as a medical practitioner",
          "id_card": "ID card",
          "medical_degree": "Medical degree",
          "exploitation_license": "Exploitation license",
          "professional_number": "Professional number",
          "professional_number_hint": "Type",
          "professional_number_error": "Professional number cannot be blank",
          "license_info": "Be patient while we verify your credentials, it will take an average of 2-4 days.",
          "add_avatar_title": "Add your avatar",
          "add_cover_title": "Add your cover",
          "add_avatar_description":
              "Avatar must be an actual photo of you. Logo, clip-art, group photos and digitally altered images are not allowed.",
          "add_cover_description":
              "Use a clear and professional image that represents your hospital or pharmacy.\nLogos, clip-art, group photos, or heavily edited images are not permitted.",
          "creating_account_title": "Assembling information",
          "creating_account_description": "Your account is being created",
          "account_submit_title": "Your account information has been submitted and is awaiting approval.",
          "account_submit_description": "This process may take 2-4 business days. Please be patient. Thanks!",
          "account_success_title": "Hooray!!!",
          "account_success_description": "You have successfully created an account.",
          "complete_profile_title": "Complete your profile",
          "missing_fields": "Missing required fields!",
          "missing_description":
              "Some of the required fields are empty or contain invalid data. Please check your input and complete before continuing.",

          //forgot password
          "forgot_password_title": "Forgot your password?",
          "forgot_password_description": "Please enter your phone number to receive a verification code",
          "phone_number_title": "Phone Number",
          "get_verification_code": "Get Verification Code",

          //create new password
          "create_new_password_title": "Create new password",
          "create_new_password_description": "Password should have at least 8 characters, include of 6 alphabets, 1 number and 1 special character",
          "confirm_password": "Confirm Password",
          "reset_password": "Reset Password",

          //doctor home
          "close": "Closed",
          "nothing_to_measure": "Nothing to measure",
          "setup_profile": "Setup your profile information first to measure your online efforts here.",
          "setup_profile_btn": "Setup profile",
          "new_booking": "New bookings",
          "upcoming_booking": "Upcoming",
          "new_rate": "new rates",
          "from_patients": "from patients",
          "dashboard": "Dashboard",
          "messages": "Messages",
          "appointments": "Appointments",
          "settings": "Settings",
          "search_nav": "Search",

          //my appointment
          "my_appointment": "My Appointments",
          "new": "New",
          "upcoming": "Upcoming",
          "history": "History",
          "no_appointment": "No appointment",
          "no_appointment_description": "You don't have any appointment yet. Let's book one now.",
          "hours_left": "hours left",
          "decline": "Decline",
          "accept": "Accept",
          "accepted": "Accepted booking",
          "patient_info": "Patient information",
          "patient_profile": "Patient's profile",
          "bill_detail": "Bill details",
          "tax_vat": "Tax VAT",
          "total": "Total paid",
          "card": "Card No",
          "bank": "Bank",
          "expire": "Exp. Date",
          "add_to_calendar": "Add to calendar",
          "reschedule": "Reschedule",
          "type": "Type",
          "duration": "Duration",
          "min": "min",
          "clinic_address": "Clinic address",
          "link": "Consulting link",
          "start_the_appointment": "Start the appointment",
          "medical_profile": "Medical profile",
          "telephone": "Telephone",
          "reason_to_reject": "Reason to reject",
          "reason_to_cancel": "Reason to cancel",
          "medical_problem": "Medical problem",
          "reject_confirm": "Do you want to reject this appointment?",
          "cancel_confirm": "Do you want to cancel this appointment?",
          "give_reason": "Give your reason",
          "leave_review": "Leave a review",
          "give_feedback": "Give feedback",
          "consultation": "Your consultation with Dr.",
          "is_over": "is over",
          "write_feedback": "Write your feedback, please",
          "comment": "Comment",
          "recommend": "Would you recommend Dr.",
          "to_friend": "to your friend and family?",
          "send_feedback": "Send feedback",
          "later": "Later",
          "appointment_status_updated": "Appointment status updated successfully",
          "review_submitted": "Review submitted successfully",
          "send_appointment_support": "Send appointment support",
          "send_appointment_support_description": "If you have any issues with your appointment, please send a support request so we can assist you.",
          "write_support_message": "Write support message",
          "message_placeholder": "Type your message here...",
          "send_support": "Send support",

          //message screen
          "message": "Message",
          "search_by_name": "Search by name",
          "no_message": "No message",
          "no_message_description": "To receive messages, you must first contact a doctor who is happy to help.",
          "no_further_message": "You have no further message...",
          "conversation": "Conversation with",
          "type_message": "Type message...",

          //setting screen
          "my_balance_wallet": "My balance wallet",
          "withdraw": "Withdraw",
          "no_balance": "No balance",
          "no_balance_description_1": "Your balance is",
          "no_balance_description_2": "please refill your wallet.",
          "no_transaction_history": "No transaction history",
          "add_balance": "Add balance",
          "to_account": "To account",
          "from": "From",
          "enter_amount": "Enter amount",
          "add_new_bank": "Add new bank account",
          "transaction_history": "Transaction history",
          "cardholder_name": "Cardholder name",
          "cardholder_hint": "Enter cardholder name",
          "card_number": "Card number",
          "card_number_hint": "Enter card number",
          "expire_date": "Expire date",
          "expire_date_hint": "Enter expire date",
          "cvv": "CVV",
          "cvv_hint": "Enter CVV",
          "save_card": "Save this card information",
          "general": "General",
          "my_profile": "My profile",
          "working_schedule": "Work schedules",
          "my_services": "My services",
          'price_required': 'Service price is required',
          'duration_required': 'Service duration is required',
          'buffer_time_required': 'Buffer time is required',
          'seats_required': 'Number of seats is required',
          "favorite_doctor": "Favorite doctors",
          "patient_records": "Patient records",
          "medical_records": "Medical records",
          "marketing": "Marketing",
          "change_password": "Change password",
          "change_language": "Change language",
          "select_language": "Select language",
          "more_setting": "More settings",
          "notification_setting": "Notification settings",
          "message_setting": "Message settings",
          "support": "Support",
          "privacy_policy": "Privacy and security",
          "logout": "Log out",
          "maximum_withdraw": "Maximum amount can be withdrawn",
          "how_many_withdraw": "How many do you want to withdraw?",
          "withdraw_to_bank": "Withdraw to bank account",
          "ammount_required": "Please enter an amount",
          "insufficient_funds": "Insufficient balance",
          "ammount_error": "Amount must be greater than 0",
          "minimum_balance": "Minimum balance after withdrawal must be 100 EUR",
          "invalid_amount": "Invalid amount",
          "failed_to_change_password": "Failed to change password",
          "failed_to_load_transactions_history": "Failed to load transaction history",
          "failed_to_load_settings": "Failed to load settings",
          "failed_to_update_settings": "Failed to update settings",
          "support_sent_successfully": "Support request sent successfully",
          "failed_to_send_support": "Failed to send support request",
          "failed_to_logout": "Failed to logout! For security reasons, Automatic logout is required.",
          "service_save_success": "Service saved successfully",
          "service_save_error": "Failed to save service",
          "work_schedule_error_1": "Please add time slots for",
          "work_schedule_error_2": "or set it as all day",
          "work_schedule_error_3": "Please fill in all start and end times for",
          "work_schedule_error_4": "End time cannot be earlier than start time",
          "work_schedule_save_success": "Work schedule saved successfully",
          "work_schedule_save_error": "Failed to save work schedule",
          
          //patient records
          "patient_records_title": "Patient records",
          "patient_records_favorite": "Favorite patients",
          "patient_empty": "You don't have any patient records",
          "favorite_patient": "Favorite Patients",
          "profile_detail": "Profile details",
          "records": "Records",

          //change password
          "change_password_title": "Change password",
          "current_password": "Current password",
          "new_password": "New password",
          "confirm_new_password": "Confirm new password",
          "confirm_password_hint": "Confirm your password",
          "reset_password_btn": "Reset password",

          //work schedule
          "work_schedule_title": "Work schedules",
          "all_day": "All day",
          "add_time": "Add time",

          //my services
          "my_services_title": "My services",
          "price": "Price",
          "active": "Active",
          "disable": "Disable",
          "amount": "Amount",
          "no_of_seats": "No. of seats",
          "work_availability": "Work availability",
          "save_changes": "Save changes",

          //notification setting
          "system_notification": "Enable system notifications",
          "system_notification_description": "Receive notification for new messages and appointments",
          "promotion_announcement": "Promotion announcement",
          "promotion_announcement_description": "Receive the earliest notifications about promotions and discounts",
          "sms_notification": "SMS notifications",
          "sms_notification_description": "Enable/Disable pop-up or banner notifications when in the app",
          "push_notification": "Push notifications",
          "push_notification_description": "Allow notifications only from specific categories (e.g., promotions, updates, reminders)",

          //message setting
          "message_delivery": "Message delivery",
          "message_delivery_description": "Auto-delete messages after a set time (e.g., 24 hours for certain chats)",
          "message_appearance": "Message appearance",
          "message_appearance_description": "Customize the appearance of the message screen (e.g., theme, chat bubbles)",
          "message_privacy": "Message privacy",
          "message_privacy_description": "Block or filter messages from unknown senders.",
          "message_backup": "Message backup",
          "message_backup_description": "Enable/Disable cloud backup for message history.",

          //logout screen
          "logout_confirm": "Are you sure you want to logout of this account?",
          "logout_description": "That’s sound sad to say goodbye. See you again in the next time.",
          "keep_stay": "Keep stay",
          "logout_btn": "Logout",

          //profile screen
          "profile": "My profile",
          "testimonials": "Testimonials",
          "service": "Services",
          "introduce": "Introduce",
          "schedule": "Schedule",
          "available": "Available",
          "rating": "Rating",
          "view_all_review": "View all reviews",
          "edit_profile": "Edit profile",
          "atttach_photo_btn": "Attach Photo",
          "not_setup": "Not setup",

          //edit profile screen
          "full_name_hint_long": "Enter your full name",
          "full_name_hint_long_2": "Enter your name",
          "full_name_label_long": "Full name",
          "full_name_label_long_2": "Name",
          "profession_label": "Enter your profession No.",
          "profession_hint": "Profession No.",
          "introduce_hint": "Enter your introduce",
          "medical_category": "Medical category",
          "office_address_label": "Office address",
          "office_address_hint": "Enter your office address",
          "country_label": "Country",
          "country_hint": "Enter your country",
          "city_label": "City",
          "city_hint": "Enter your city",
          "GPS_label": "GPS",
          "GPS_hint": "Enter your latitude, Longitude",
          "company_name_label": "Company - Institution",
          "company_name_hint": "Enter your company - institution",
          "profile_update_success": "Profile updated successfully",

          //feedback screen
          "feedback": "Feedback",
          "no_feedback": "No feedback",

          //notification screen
          "notification": "Notifications",
          "all_notification": "All notifications", 
          "no_notification": "No notifications",
          "no_notification_description": "You have no new notifications yet.",
          "detail": "Detail",
          "has_made_an_appointment": "has made an appointment",
          "canceled_your_appointment": "canceled your appointment",

          //search screen
          "what_are_you_looking_for": "What're you looking for?",
          "suggest_main": "Suggested main sections",
          "browse_doctors_nearby": "Browse doctors nearby",
          "browse_hospitals_nearby": "Browse hospitals nearby",
          "browse_pharmacy_nearby": "Browse pharmacies nearby",
          "emergency_lines": "Emergency lines",
          "popular": "Popular",
          "price_from": "Price from",
          "book_appointment": "Book appointment",
          "busy": "Busy",
          "opening": "Opening",
          "closed": "Closed",
          "view_direction": "View direction",
          "available_time": "Available time",
          "all_schedules_available": "All schedules available",
          "not_rated": "Not rated",

          //booking screen
          "choose_services": "Choose services",
          "choose_time": "Choose time",
          "another_person": "Another person",
          "country": "Country",
          "state": "State",
          "city": "City",
          "zip_code": "Zip code",
          "summarize_medical": "Summarize your medical problem",
          "enter_history": "Enter your history medical",
          "note": "Note",
          "add_voice": "Add voice",
          "attach_file": "Attach file",
          "review_schedule": "Review schedule",
          "time&date": "Time & Date",
          "gps_location": "GPS location",
          "payment_method": "Payment method",
          "payment": "Payment",
          "add_new_card": "Add new card",
          "choose_a_method": "Choose a method",
          "no_card": "Haven't added any card yet",
          "choose_your_payment": "Choose your payment method",
          "confirm_payment": "Confirm payment",
          "swipe_to_pay": "Swipe to pay",
          "booking_success": "Thanks, your appointment has been booked successfully!",
          "booking_success_description": "Please check your appointment history for receipt and booking details.",
          "call": "Call",
          "see_all_detail": "See all detail",
          "back_to_home": "Back to home",
          "booked_success": "Booked successfully",
          "please_select_a_payment_method": "Please select a payment method",

          //common
          "yes": "Yes",
          "no": "No",
          "home_visit": "Home visit",
          "completed": "Completed",
          "filter": "Filter",
          "location": "Location",
          "contact": "Contact",
          "language": "Language",
          "insurance": "Insurance",
          "information": "Information",
          "empty": "Empty",
          "enter": "Enter",
          "submit": "Submit",
          "save": "Save",
          "description": "Description",
          "rejected": "Rejected",
          "reject": "Reject",
          "cancelled": "Cancelled",
          "date": "Date",
          "time": "Time",
          "address": "Address",
          "cancel": "Cancel",
          "search": "Search...",
          "search_2": "Search",
          "skip": "Skip",
          "check": "Check",
          "enter_number": "Enter number",
          "number": "Number",
          "continue_btn": "Continue",
          "attach_photo_btn": "Attach Photo",
          "complete_btn": "Complete",
          "ok_btn": "OK got it",
          "app_name": "DoctaMobile",
          "email_label": "Email",
          "email_hint": "Enter your email",
          "email_error_blank": "Email is cannot be blank",
          "email_error_invalid": "Email is invalid",
          "password_label": "Password",
          "password_hint": "Enter your password",
          "password_error_blank": "Password is cannot be blank",
          "password_error_invalid": "Password is invalid",
          "password_strength": "Password should have at least 8 characters, include of 6 alphabets, 1 number and 1 special character (&, \$, #, %).",
          "and": "and ",
          "im": "I'm ",
          "choose": "Choose",
          "problem_description": "Problem description",
          "upload": "Upload",
          "typing": "Typing...",
          "send": "Send",
          "add": "Add",

          "full_name_label": "Full Name",
          "full_name_hint": "Your full name",
          "full_name_error": "Full name cannot be blank",
          "age_label": "Age",
          "gender_label": "Gender",
          "gender_option_1": "Male",
          "gender_option_2": "Female",
          "gender_option_3": "Other",
          "height_label": "Height",
          "weight_label": "Weight",
          "blood_group_label": "Blood group",
          "medical_history_label": "Medical history",
          "medical_history_hint": "Enter your history medical",
          "medical_history_error": "Medical history cannot be blank",
          "insurance_type_label": "Insurance type",
          "insurance_type_option_1": "Public insurance",
          "insurance_type_option_2": "Private insurance",
          "insurance_type_option_3": "Vietnamese insurance",
          "public_insurance": "Public insurance",
          "private_insurance": "Private insurance",
          "insurance_number_label": "Insurance number",
          "insurance_error": "Insurance number cannot be blank",
          "assurances_type": "Assurances type",
          "assurances_type_option_1": "Life Insurance (Basic)",
          "assurances_type_option_2": "Life Insurance (Premium)",
          "assurances_type_option_3": "Togo Medicare C12 (Basic)",
          "assurances_type_option_4": "Togo Medicare B18 (Premium)",
          "assurances_type_option_5": "Senior Health Insur Plan A1",
          "assurances_type_option_6": "Senior Health Insur Plan B2",
          "main_insured": "Main insured",
          "main_insured_error": "Main insured cannot be blank",
          "entitled_insured": "Entitled insured",
          "entitled_insured_error": "Entitled insured cannot be blank",
          "insurance_registry_label": "Insurance registration",
          "insurance_registry_hint": "Enter your insurance registration",
          "insurance_registry_error": "Insurance registration cannot be blank",
          "insurance_registry_address_label": "Insurance registration address",
          "insurance_registry_address_hint": "Enter your insurance registration address",
          "insurance_registry_address_error": "Insurance registration address cannot be blank",
          "insurance_vaild_from_label": "Insurance valid from",
          "insurance_vaild_from_hint": "Enter the date",
          "insurance_vaild_from_error": "Insurance valid from cannot be blank",
          "address_label": "Address",
          "address_hint": "Enter",
          "address_error": "Address cannot be blank",

          "invalid_file_type": "Invalid file type",
          "please_select_file": "Please select a JPG or PNG image",

          "file_too_large": "File too large",
          "image_size_limit": "Image file size must not exceed 5MB.",

          //payment result
          'payment_success': "Thanks, your appointment has been booked successfully!",
          'payment_success_description': "Please check your appointment history for receipt and booking details.",

          //error messages
          "full_fill_required": "Please full fill all require fields",

          "error": "Error",
          "success": "Success",
          "warning": "Warning",
        },
        'vi_VN': {
          "currency": "₫",
          //splash screen
          "splash_title": "Chăm sóc sức khỏe chỉ\nmột chạm",
          "login": "Đăng nhập",
          "sign_up": "Tạo tài khoản",
          "or": "hoặc tiếp tục với",

          //login screen
          "welcome_back": "Chào mừng trở lại!",
          "login_label": "Email",
          "login_hint": "Nhập",
          "forgot_password": "Quên mật khẩu?",
          "login_btn": "Đăng nhập",
          "login_error_not_exist": "Tài khoản không tồn tại",
          "login_error_not_correct": "Ops! Email/Số điện thoại hoặc mật khẩu không chính xác",
          "login_error_suspended": "Tài khoản của bạn đã bị tạm ngừng",
          "login_error_not_approved": "Tài khoản của bạn đang chờ phê duyệt",

          //telephone screen
          "enter_phone_number": "Nhập số điện thoại của bạn",
          "phone_number": "Số điện thoại",
          "info": "Đừng lo lắng. Chúng tôi sẽ không nhắn tin hay gọi cho bạn. Chúng tôi sẽ gửi mã 4 chữ số để xác nhận tài khoản.",

          //verify screen
          "verify_title": "Nhập mã 4 chữ số chúng tôi đã gửi đến",
          "resend_code": "Gửi lại mã",
          "resend_code_after": "Gửi lại mã sau",
          "wrong": "Mã sai",
          "verify_btn": "Xác minh",

          //user type screen
          "user_type_title": "Chào mừng đến với",
          "user_type_subtitle": "Bạn đang tìm kiếm\ngì?",
          "user_type_doctor_title": "Cung cấp trợ giúp",
          "user_type_doctor_subtitle": "Tôi là nhà cung cấp dịch vụ y tế",
          "user_type_patient_title": "Cần trợ giúp",
          "user_type_patient_subtitle": "Tôi là bệnh nhân",

          //create account screen
          "emailExist": "Email đã tồn tại!",
          "create_account_title": "Tạo tài khoản của bạn",
          "agree_terms": "Bằng cách đăng ký, bạn đồng ý với ",
          "terms": "Điều khoản & Điều kiện \n",
          "privacy": "Chính sách bảo mật",
          "identity_title": "Bạn là ai?",
          "doctor": "Bác sĩ",
          "pharmacy": "Nhà thuốc",
          "hospital": "Bệnh viện",
          "ambulance": "Xe cứu thương",
          "license_title": "Tải lên giấy phép và bằng cấp",
          "license_description": "Vui lòng xác minh thông tin đăng ký của bạn như một bác sĩ",
          "id_card": "Thẻ căn cước",
          "medical_degree": "Bằng y khoa",
          "exploitation_license": "Giấy phép hành nghề",
          "professional_number": "Số bác sĩ",
          "professional_number_hint": "Nhập",
          "professional_number_error": "Số bác sĩ không thể để trống",
          "license_info": "Hãy kiên nhẫn trong khi chúng tôi xác minh thông tin của bạn, quá trình này mất trung bình 2-4 ngày.",
          "add_avatar_title": "Thêm ảnh đại diện",
          "add_cover_title": "Thêm ảnh bìa",
          "add_avatar_description": "Ảnh đại diện phải là ảnh thật của bạn. Logo, hình minh họa, ảnh nhóm và ảnh chỉnh sửa kỹ thuật số không được phép.",
          "add_cover_description": "Sử dụng hình ảnh rõ ràng và chuyên nghiệp đại diện cho bệnh viện hoặc nhà thuốc của bạn.\nLogo, hình minh họa, ảnh nhóm hoặc hình ảnh chỉnh sửa nhiều không được phép.",
          "creating_account_title": "Đang tập hợp thông tin",
          "creating_account_description": "Tài khoản của bạn đang được tạo",
          "account_submit_title": "Thông tin tài khoản của bạn đã được gửi và đang chờ phê duyệt.",
          "account_submit_description": "Quá trình này có thể mất 2-4 ngày làm việc. Vui lòng kiên nhẫn. Cảm ơn!",
          "account_success_title": "Hooray!!!",
          "account_success_description": "Bạn đã tạo tài khoản thành công.",
          "complete_profile_title": "Hoàn thiện hồ sơ",
          "missing_fields": "Thiếu trường bắt buộc!",
          "missing_description": "Một số trường bắt buộc đang trống hoặc chứa dữ liệu không hợp lệ. Vui lòng kiểm tra và hoàn thành trước khi tiếp tục.",

          //forgot password
          "forgot_password_title": "Quên mật khẩu?",
          "forgot_password_description": "Vui lòng nhập số điện thoại để nhận mã xác minh",
          "phone_number_title": "Số điện thoại",
          "get_verification_code": "Nhận mã xác minh",

          //create new password
          "create_new_password_title": "Tạo mật khẩu mới",
          "create_new_password_description": "Mật khẩu phải có ít nhất 8 ký tự, bao gồm 6 chữ cái, 1 số và 1 ký tự đặc biệt",
          "confirm_password": "Xác nhận mật khẩu",
          "reset_password": "Đặt lại mật khẩu",

          //doctor home
          "close": "Nghỉ ngơi",
          "nothing_to_measure": "Không có gì để đo",
          "setup_profile": "Thiết lập thông tin hồ sơ trước để đo lường nỗ lực trực tuyến của bạn ở đây.",
          "setup_profile_btn": "Thiết lập hồ sơ",
          "new_booking": "Đặt lịch mới",
          "upcoming_booking": "Sắp tới",
          "new_rate": "đánh giá mới",
          "from_patients": "từ bệnh nhân",
          "dashboard": "Trang chủ",
          "messages": "Tin nhắn",
          "appointments": "Cuộc hẹn",
          "settings": "Cài đặt",
          "search_nav": "Tìm kiếm",

          //my appointment
          "my_appointment": "Cuộc hẹn của tôi",
          "new": "Mới",
          "upcoming": "Sắp tới",
          "history": "Lịch sử",
          "no_appointment": "Không có cuộc hẹn",
          "no_appointment_description": "Bạn chưa có cuộc hẹn nào. Hãy đặt lịch ngay.",
          "hours_left": "giờ còn lại",
          "decline": "Từ chối",
          "accept": "Chấp nhận",
          "accepted": "Đã chấp nhận đặt lịch",
          "patient_info": "Thông tin bệnh nhân",
          "patient_profile": "Hồ sơ bệnh nhân",
          "doctor_profile": "Hồ sơ bác sĩ",
          "bill_detail": "Chi tiết hóa đơn",
          "tax_vat": "Thuế VAT",
          "total": "Tổng thanh toán",
          "card": "Số thẻ",
          "bank": "Ngân hàng",
          "expire": "Ngày hết hạn",
          "add_to_calendar": "Thêm vào lịch",
          "reschedule": "Đổi lịch",
          "type": "Loại",
          "duration": "Thời lượng",
          "min": "phút",
          "clinic_address": "Địa chỉ phòng khám",
          "link": "Liên kết tư vấn",
          "start_the_appointment": "Bắt đầu cuộc hẹn",
          "medical_profile": "Hồ sơ y tế",
          "telephone": "Điện thoại",
          "reason_to_reject": "Lý do từ chối",
          "reason_to_cancel": "Lý do hủy",
          "medical_problem": "Vấn đề y tế",
          "reject_confirm": "Bạn có muốn từ chối cuộc hẹn này?",
          "cancel_confirm": "Bạn có muốn hủy cuộc hẹn này?",
          "give_reason": "Đưa ra lý do",
          "leave_review": "Để lại đánh giá",
          "give_feedback": "Đưa ra phản hồi",
          "consultation": "Cuộc tư vấn của bạn với BS.",
          "is_over": "đã kết thúc",
          "write_feedback": "Viết phản hồi của bạn",
          "comment": "Bình luận",
          "recommend": "Bạn có khuyến nghị BS.",
          "to_friend": "cho bạn bè và gia đình?",
          "send_feedback": "Gửi phản hồi",
          "later": "Để sau",
          "appointment_status_updated": "Trạng thái cuộc hẹn đã được cập nhật thành công",
          "review_submitted": "Đánh giá đã được gửi thành công",
          "send_appointment_support": "Gửi yêu cầu hỗ trợ lịch hẹn",
          "send_appointment_support_description": "Nếu bạn gặp sự cố với cuộc hẹn, vui lòng gửi yêu cầu hỗ trợ để chúng tôi có thể giúp đỡ bạn.",
          "write_support_message": "Viết tin nhắn hỗ trợ",
          "message_placeholder": "Nhập tin nhắn của bạn ở đây...",
          "send_support": "Gửi hỗ trợ",

          //message screen
          "message": "Tin nhắn",
          "search_by_name": "Tìm theo tên",
          "no_message": "Không có tin nhắn",
          "no_message_description": "Để nhận tin nhắn, bạn phải liên hệ với bác sĩ sẵn sàng giúp đỡ.",
          "no_further_message": "Bạn không có tin nhắn nào khác...",
          "conversation": "Cuộc trò chuyện với",
          "type_message": "Nhập tin nhắn...",

          //setting screen
          "my_balance_wallet": "Ví số dư của tôi",
          "withdraw": "Rút tiền",
          "no_balance": "Không có số dư",
          "no_balance_description_1": "Số dư của bạn hiện là",
          "no_balance_description_2": "vui lòng nạp tiền vào ví.",
          "no_transaction_history": "Không có lịch sử giao dịch",
          "add_balance": "Thêm số dư",
          "to_account": "Đến tài khoản",
          "from": "Từ",
          "enter_amount": "Nhập số tiền",
          "add_new_bank": "Thêm tài khoản ngân hàng mới",
          "transaction_history": "Lịch sử giao dịch",
          "cardholder_name": "Tên chủ thẻ",
          "cardholder_hint": "Nhập tên chủ thẻ",
          "card_number": "Số thẻ",
          "card_number_hint": "Nhập số thẻ",
          "expire_date": "Ngày hết hạn",
          "expire_date_hint": "Nhập ngày hết hạn",
          "cvv": "CVV",
          "cvv_hint": "Nhập CVV",
          "save_card": "Lưu thông tin thẻ này",
          "general": "Tổng quan",
          "my_profile": "Hồ sơ của tôi",
          "working_schedule": "Lịch làm việc",
          "my_services": "Dịch vụ của tôi",
          'price_required': 'Giá dịch vụ là bắt buộc',
          'duration_required': 'Thời lượng dịch vụ là bắt buộc',
          'buffer_time_required': 'Thời gian đệm là bắt buộc',
          'seats_required': 'Số lượng chỗ ngồi là bắt buộc',
          "favorite_doctor": "Bác sĩ yêu thích",
          "patient_records": "Hồ sơ bệnh nhân",
          "medical_records": "Hồ sơ y tế",
          "marketing": "Tiếp thị",
          "change_password": "Đổi mật khẩu",
          "change_language": "Đổi ngôn ngữ",
          "select_language": "Chọn ngôn ngữ",
          "more_setting": "Cài đặt khác",
          "notification_setting": "Cài đặt thông báo",
          "message_setting": "Cài đặt tin nhắn",
          "support": "Hỗ trợ",
          "privacy_policy": "Bảo mật và quyền riêng tư",
          "logout": "Đăng xuất",
          "maximum_withdraw": "Số tiền tối đa có thể rút",
          "how_many_withdraw": "Bạn muốn rút bao nhiêu?",
          "withdraw_to_bank": "Rút về tài khoản ngân hàng",
          "ammount_required": "Vui lòng nhập số tiền",
          "insufficient_funds": "Số dư không đủ",
          "ammount_error": "Số tiền phải lớn hơn 0",
          "minimum_balance": "Số dư tối thiểu sau khi rút phải là 1 000 000 ₫",
          "invalid_amount": "Số tiền không hợp lệ",
          "failed_to_change_password": "Đổi mật khẩu không thành công",
          "failed_to_load_transactions_history": "Không thể tải lịch sử giao dịch",
          "failed_to_load_settings": "Không thể tải cài đặt",
          "failed_to_update_settings": "Không thể cập nhật cài đặt",
          "support_sent_successfully": "Yêu cầu hỗ trợ đã được gửi thành công",
          "failed_to_send_support": "Không thể gửi yêu cầu hỗ trợ",
          "failed_to_logout": "Đăng xuất không thành công! Để đảm bảo an toàn, Tự động đăng xuất.",
          "service_save_success": "Dịch vụ đã được lưu thành công",
          "service_save_error": "Lỗi khi lưu dịch vụ",
          "work_schedule_error_1": "Hãy thêm 1 giờ làm việc cho ngày",
          "work_schedule_error_2": "hoặc đặt làm việc cả ngày",
          "work_schedule_error_3": "Vui lòng điền đầy đủ giờ bắt đầu và kết thúc cho ngày",
          "work_schedule_error_4": "Giờ kết thúc không thể sớm hơn giờ bắt đầu",
          "work_schedule_save_success": "Lịch làm việc đã được lưu thành công",
          "work_schedule_save_error": "Lỗi khi lưu lịch làm việc",

          //patient records
          "patient_records_title": "Hồ sơ bệnh nhân",
          "patient_records_favorite": "Bệnh nhân yêu thích",
          "patient_empty": "Bạn không có hồ sơ bệnh nhân nào",
          "favorite_patient": "Bệnh nhân yêu thích",
          "profile_detail": "Chi tiết hồ sơ",
          "records": "Hồ sơ",

          //change password
          "change_password_title": "Đổi mật khẩu",
          "current_password": "Mật khẩu hiện tại",
          "new_password": "Mật khẩu mới",
          "confirm_new_password": "Xác nhận mật khẩu mới",
          "confirm_password_hint": "Xác nhận mật khẩu",
          "reset_password_btn": "Đặt lại mật khẩu",

          //work schedule
          "work_schedule_title": "Lịch làm việc",
          "all_day": "Cả ngày",
          "add_time": "Thêm thời gian",

          //my services
          "my_services_title": "Dịch vụ của tôi",
          "price": "Giá",
          "active": "Hoạt động",
          "disable": "Tắt",
          "amount": "Số tiền",
          "no_of_seats": "Số chỗ ngồi",
          "work_availability": "Tình trạng làm việc",
          "save_changes": "Lưu thay đổi",

          //notification setting
          "system_notification": "Bật thông báo hệ thống",
          "system_notification_description": "Nhận thông báo về tin nhắn và cuộc hẹn mới",
          "promotion_announcement": "Thông báo khuyến mại",
          "promotion_announcement_description": "Nhận thông báo sớm nhất về khuyến mại và giảm giá",
          "sms_notification": "Thông báo SMS",
          "sms_notification_description": "Bật/Tắt thông báo pop-up hoặc banner khi trong ứng dụng",
          "push_notification": "Thông báo đẩy",
          "push_notification_description": "Chỉ cho phép thông báo từ các danh mục cụ thể (vd: khuyến mại, cập nhật, nhắc nhở)",

          //message setting
          "message_delivery": "Gửi tin nhắn",
          "message_delivery_description": "Tự động xóa tin nhắn sau một thời gian nhất định (vd: 24 giờ cho một số cuộc trò chuyện)",
          "message_appearance": "Giao diện tin nhắn",
          "message_appearance_description": "Tùy chỉnh giao diện màn hình tin nhắn (vd: chủ đề, bong bóng chat)",
          "message_privacy": "Quyền riêng tư tin nhắn",
          "message_privacy_description": "Chặn hoặc lọc tin nhắn từ người gửi không xác định.",
          "message_backup": "Sao lưu tin nhắn",
          "message_backup_description": "Bật/Tắt sao lưu đám mây cho lịch sử tin nhắn.",

          //logout screen
          "logout_confirm": "Bạn có chắc chắn muốn đăng xuất khỏi tài khoản này?",
          "logout_description": "Thật buồn khi phải nói lời tạm biệt. Hẹn gặp lại lần sau.",
          "keep_stay": "Tiếp tục ở lại",
          "logout_btn": "Đăng xuất",

          //profile screen
          "profile": "Hồ sơ của tôi",
          "testimonials": "Tổng quan đánh giá",
          "service": "Dịch vụ",
          "introduce": "Giới thiệu",
          "schedule": "Lịch trình",
          "available": "Có sẵn",
          "rating": "Đánh giá",
          "view_all_review": "Xem tất cả đánh giá",
          "edit_profile": "Chỉnh sửa hồ sơ",
          "atttach_photo_btn": "Đính kèm ảnh",
          "not_setup": "Chưa thiết lập",

          //edit profile screen
          "full_name_hint_long": "Nhập họ tên đầy đủ",
          "full_name_hint_long_2": "Nhập tên",
          "full_name_label_long": "Họ tên đầy đủ",
          "full_name_label_long_2": "Tên",
          "profession_label": "Nhập số chuyên nghiệp",
          "profession_hint": "Số chuyên nghiệp",
          "introduce_hint": "Nhập giới thiệu",
          "medical_category": "Danh mục y tế",
          "office_address_label": "Địa chỉ văn phòng",
          "office_address_hint": "Nhập địa chỉ văn phòng",
          "country_label": "Quốc gia",
          "country_hint": "Nhập quốc gia",
          "city_label": "Thành phố",
          "city_hint": "Nhập thành phố",
          "GPS_label": "GPS",
          "GPS_hint": "Nhập vĩ độ, kinh độ",
          "company_name_label": "Công ty - Tổ chức",
          "company_name_hint": "Nhập công ty - tổ chức",
          "profile_update_success": "Hồ sơ đã cập nhật thành công",

          //feedback screen
          "feedback": "Phản hồi",
          "no_feedback": "Không có phản hồi",

          //notification screen
          "notification": "Thông báo",
          "all_notification": "Tất cả thông báo",
          "no_notification": "Không có thông báo",
          "no_notification_description": "Bạn chưa có thông báo mới nào.",
          "detail": "Chi tiết",
          "has_made_an_appointment": "đã đặt lịch hẹn",
          "canceled_your_appointment": "đã hủy cuộc hẹn của bạn",

          //search screen
          "what_are_you_looking_for": "Bạn đang tìm kiếm gì?",
          "suggest_main": "Đề xuất các mục chính",
          "browse_doctors_nearby": "Duyệt bác sĩ gần đây",
          "browse_hospitals_nearby": "Duyệt bệnh viện gần đây",
          "browse_pharmacy_nearby": "Duyệt nhà thuốc gần đây",
          "emergency_lines": "Đường dây khẩn cấp",
          "popular": "Phổ biến",
          "price_from": "Giá từ",
          "book_appointment": "Đặt lịch hẹn",
          "busy": "Bận",
          "opening": "Đang mở",
          "closed": "Đã đóng",
          "view_direction": "Xem hướng",
          "available_time": "Thời gian có sẵn",
          "all_schedules_available": "Tất cả lịch trình có sẵn",
          "not_rated": "Mới",

          //booking screen
          "choose_services": "Chọn dịch vụ",
          "choose_time": "Chọn thời gian",
          "another_person": "Người khác",
          "country": "Quốc gia",
          "state": "Tỉnh/Bang",
          "city": "Thành phố",
          "zip_code": "Mã bưu điện",
          "summarize_medical": "Tóm tắt vấn đề y tế của bạn",
          "enter_history": "Nhập lịch sử y tế",
          "note": "Ghi chú",
          "add_voice": "Thêm giọng nói",
          "attach_file": "Đính kèm tệp",
          "review_schedule": "Xem lại lịch trình",
          "time&date": "Thời gian & Ngày",
          "gps_location": "Vị trí GPS",
          "payment_method": "Phương thức thanh toán",
          "payment": "Thanh toán",
          "add_new_card": "Thêm thẻ mới",
          "choose_a_method": "Chọn phương thức",
          "no_card": "Chưa thêm thẻ nào",
          "choose_your_payment": "Chọn phương thức thanh toán",
          "confirm_payment": "Xác nhận thanh toán",
          "swipe_to_pay": "Vuốt để thanh toán",
          "booking_success": "Cảm ơn, cuộc hẹn của bạn đã được đặt thành công!",
          "booking_success_description": "Vui lòng kiểm tra lịch sử cuộc hẹn để xem biên lai và chi tiết đặt lịch.",
          "call": "Gọi",
          "see_all_detail": "Xem tất cả chi tiết",
          "back_to_home": "Về trang chủ",
          "booked_success": "Đặt lịch thành công",
          "please_select_a_payment_method": "Vui lòng chọn phương thức thanh toán",

          //common
          "yes": "Có",
          "no": "Không",
          "home_visit": "Khám tại nhà",
          "completed": "Hoàn thành",
          "filter": "Lọc",
          "location": "Vị trí",
          "contact": "Liên hệ",
          "language": "Ngôn ngữ",
          "insurance": "Bảo hiểm",
          "information": "Thông tin",
          "empty": "Trống",
          "enter": "Nhập",
          "submit": "Gửi",
          "save": "Lưu",
          "description": "Mô tả",
          "rejected": "Đã từ chối",
          "reject": "Từ chối",
          "cancelled": "Đã hủy",
          "date": "Ngày",
          "time": "Thời gian",
          "address": "Địa chỉ",
          "cancel": "Hủy",
          "search": "Tìm kiếm...",
          "search_2": "Tìm kiếm",
          "skip": "Bỏ qua",
          "check": "Kiểm tra",
          "enter_number": "Nhập số",
          "number": "Số",
          "continue_btn": "Tiếp tục",
          "attach_photo_btn": "Đính kèm ảnh",
          "complete_btn": "Hoàn thành",
          "ok_btn": "OK hiểu rồi",
          "app_name": "DoctaMobile",
          "email_label": "Email",
          "email_hint": "Nhập email",
          "email_error_blank": "Email không thể để trống",
          "email_error_invalid": "Email không hợp lệ",
          "password_label": "Mật khẩu",
          "password_hint": "Nhập mật khẩu",
          "password_error_blank": "Mật khẩu không thể để trống",
          "password_error_invalid": "Mật khẩu không hợp lệ",
          "password_strength": "Mật khẩu phải có ít nhất 8 ký tự, bao gồm 6 chữ cái, 1 số và 1 ký tự đặc biệt (&, \$, #, %).",
          "and": "và ",
          "im": "Tôi là ",
          "choose": "Chọn",
          "problem_description": "Mô tả vấn đề",
          "upload": "Tải lên",
          "typing": "Đang nhập...",
          "send": "Gửi",
          "add": "Thêm",

          "full_name_label": "Họ tên đầy đủ",
          "full_name_hint": "Họ tên đầy đủ của bạn",
          "full_name_error": "Họ tên đầy đủ không thể để trống",
          "age_label": "Tuổi",
          "gender_label": "Giới tính",
          "gender_option_1": "Nam",
          "gender_option_2": "Nữ",
          "gender_option_3": "Khác",
          "height_label": "Chiều cao",
          "weight_label": "Cân nặng",
          "blood_group_label": "Nhóm máu",
          "medical_history_label": "Lịch sử y tế",
          "medical_history_hint": "Nhập lịch sử y tế",
          "medical_history_error": "Lịch sử y tế không thể để trống",
          "insurance_type_label": "Loại bảo hiểm",
          "insurance_type_option_1": "Bảo hiểm công",
          "insurance_type_option_2": "Bảo hiểm tư",
          "insurance_type_option_3": "Bảo hiểm Việt Nam",
          "public_insurance": "Bảo hiểm công",
          "private_insurance": "Bảo hiểm tư",
          "insurance_number_label": "Số bảo hiểm",
          "insurance_error": "Số bảo hiểm không thể để trống",
          "assurances_type": "Loại bảo hiểm",
          "assurances_type_option_1": "Bảo hiểm nhân thọ (Cơ bản)",
          "assurances_type_option_2": "Bảo hiểm nhân thọ (Cao cấp)",
          "assurances_type_option_3": "Togo Medicare C12 (Cơ bản)",
          "assurances_type_option_4": "Togo Medicare B18 (Cao cấp)",
          "assurances_type_option_5": "Gói bảo hiểm sức khỏe người cao tuổi A1",
          "assurances_type_option_6": "Gói bảo hiểm sức khỏe người cao tuổi B2",
          "main_insured": "Người được bảo hiểm chính",
          "main_insured_error": "Người được bảo hiểm chính không thể để trống",
          "entitled_insured": "Người được bảo hiểm có quyền",
          "entitled_insured_error": "Người được bảo hiểm có quyền không thể để trống",
          "insurance_registry_label": "Đăng ký bảo hiểm",
          "insurance_registry_hint": "Nhập đăng ký bảo hiểm",
          "insurance_registry_error": "Đăng ký bảo hiểm không thể để trống",
          "insurance_registry_address_label": "Địa chỉ đăng ký bảo hiểm",
          "insurance_registry_address_hint": "Nhập địa chỉ đăng ký bảo hiểm",
          "insurance_registry_address_error": "Địa chỉ đăng ký bảo hiểm không thể để trống",
          "insurance_vaild_from_label": "Bảo hiểm có hiệu lực từ",
          "insurance_vaild_from_hint": "Nhập ngày",
          "insurance_vaild_from_error": "Bảo hiểm có hiệu lực từ không thể để trống",
          "address_label": "Địa chỉ",
          "address_hint": "Nhập",
          "address_error": "Địa chỉ không thể để trống",

          "invalid_file_type": "Loại tệp không hợp lệ",
          "please_select_file": "Vui lòng chọn tệp hình ảnh JPG hoặc PNG",

          "file_too_large": "Tệp quá lớn",
          "image_size_limit": "Kích thước tệp hình ảnh không được vượt quá 5MB.",

          //payment result
          'payment_success': "Cảm ơn, cuộc hẹn của bạn đã được đặt thành công!",
          'payment_success_description': "Vui lòng kiểm tra lịch sử cuộc hẹn để xem biên lai và chi tiết đặt lịch.",

          //error
          "full_fill_required": "Xin vui lòng điền đầy đủ các trường bắt buộc.",

          "error": "Lỗi",
          "success": "Thành công",
          "warning": "Cảnh báo",
        },
      };
}
