import 'package:medlink/utils/app_imports.dart';

class Words extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          //splash screen
          "splash_title": "Health Care is a\ntouch away",
          "login": "Log In",
          "sign_up": "Create an Account",
          "or": "or continue with",

          //login screen
          "welcome_back": "Welcome back!",
          "login_label": "Email",
          "login_hint": "Type",
          "forgot_password": "Forgot Password?",
          "login_btn": "Log In",
          "login_error_not_exist": "Account does not exist",
          "login_error_not_correct": "Oops! Email/Phone number or password is not correct",
          "login_error_suspended": "Your account has been suspended",
          "login_error_not_approved": "Your account is waiting for approval",

          //telephone screen
          "enter_phone_number": "Enter your phone number",
          "phone_number": "Phone number",
          "info": "Don't worry. We won't text you or call you. We'll send you a 4-digit code to confirm your account.",

          //verify screen
          "verify_title": "Enter the 4-digit code we sent to",
          "resend_code": "Resend code",
          "resend_code_after": "Resend code after",
          "wrong": "Wrong code",
          "verify_btn": "Verify",

          //user type screen
          "user_type_title": "Welcome to",
          "user_type_subtitle": "What are you\nlooking for?",
          "user_type_doctor_title": "Provide help",
          "user_type_doctor_subtitle": "I'm a healthcare provider",
          "user_type_patient_title": "Need help",
          "user_type_patient_subtitle": "I'm a patient member",

          //create account screen
          "emailExist": "Email already exists!",
          "create_account_title": "Create your account",
          "agree_terms": "By registering, you agree to our ",
          "terms": "Terms & Conditions \n",
          "privacy": "Privacy Policy",
          "identity_title": "Who are you ?",
          "doctor": "Doctor",
          "pharmacy": "Pharmacy",
          "hospital": "Hospital",
          "ambulance": "Ambulance",
          "license_title": "Upload license and doctorate",
          "license_description": "Please verify your credentials as a medical practitioner",
          "id_card": "ID card",
          "medical_degree": "Medical degree",
          "exploitation_license": "Exploitation license",
          "professional_number": "Professional number",
          "professional_number_hint": "Type",
          "professional_number_error": "Professional number cannot be blank",
          "license_info": "Be patient while we verify your credentials, it will take an average of 2-4 days.",
          "add_avatar_title": "Add your avatar",
          "add_cover_title": "Add your cover",
          "add_avatar_description":
              "Avatar must be an actual photo of you. Logo, clip-art, group photos and digitally altered images are not allowed.",
          "add_cover_description":
              "Use a clear and professional image that represents your hospital or pharmacy.\nLogos, clip-art, group photos, or heavily edited images are not permitted.",
          "creating_account_title": "Assembling information",
          "creating_account_description": "Your account is being created",
          "account_submit_title": "Your account information has been submitted and is awaiting approval.",
          "account_submit_description": "This process may take 2-4 business days. Please be patient. Thanks!",
          "account_success_title": "Hooray!!!",
          "account_success_description": "You have successfully created an account.",
          "complete_profile_title": "Complete your profile",
          "missing_fields": "Missing required fields!",
          "missing_description":
              "Some of the required fields are empty or contain invalid data. Please check your input and complete before continuing.",

          //forgot password
          "forgot_password_title": "Forgot your password?",
          "forgot_password_description": "Please enter your phone number to receive a verification code",
          "phone_number_title": "Phone Number",
          "get_verification_code": "Get Verification Code",

          //create new password
          "create_new_password_title": "Create new password",
          "create_new_password_description": "Password should have at least 8 characters, include of 6 alphabets, 1 number and 1 special character",
          "confirm_password": "Confirm Password",
          "reset_password": "Reset Password",

          //doctor home
          "close": "Closed",
          "nothing_to_measure": "Nothing to measure",
          "setup_profile": "Setup your profile information first to measure your online efforts here.",
          "setup_profile_btn": "Setup profile",
          "new_booking": "New bookings",
          "upcoming_booking": "Upcoming",
          "new_rate": "new rates",
          "from_patients": "from patients",

          //my appointment
          "my_appointment": "My Appointments",
          "new": "New",
          "upcoming": "Upcoming",
          "history": "History",
          "no_appointment": "No appointment",
          "no_appointment_description": "You don't have any appointment yet. Let's book one now.",
          "hours_left": "hours left",
          "decline": "Decline",
          "accept": "Accept",
          "accepted": "Accepted booking",
          "patient_info": "Patient information",
          "patient_profile": "Patient's profile",
          "bill_detail": "Bill details",
          "tax_vat": "Tax VAT",
          "total": "Total paid",
          "card": "Card No",
          "bank": "Bank",
          "expire": "Exp. Date",
          "add_to_calendar": "Add to calendar",
          "reschedule": "Reschedule",
          "type": "Type",
          "duration": "Duration",
          "min": "min",
          "clinic_address": "Clinic address",
          "link": "Consulting link",
          "start_the_appointment": "Start the appointment",
          "medical_profile": "Medical profile",
          "telephone": "Telephone",
          "reason_to_reject": "Reason to reject",
          "reason_to_cancel": "Reason to cancel",
          "medical_problem": "Medical problem",
          "reject_confirm": "Do you want to reject this appointment?",
          "cancel_confirm": "Do you want to cancel this appointment?",
          "give_reason": "Give your reason",
          "leave_review": "Leave a review",
          "give_feedback": "Give feedback",
          "consultation": "Your consultation with Dr.",
          "is_over": "is over",
          "write_feedback": "Write your feedback, please",
          "comment": "Comment",
          "recommend": "Would you recommend Dr.",
          "to_friend": "to your friend and family?",
          "send_feedback": "Send feedback",
          "later": "Later",

          //message screen
          "message": "Message",
          "search_by_name": "Search by name",
          "no_message": "No message",
          "no_message_description": "To receive messages, you must first contact a doctor who is happy to help.",
          "no_further_message": "You have no further message...",
          "conversation": "Conversation with",
          "type_message": "Type message...",

          //setting screen
          "my_balance_wallet": "My balance wallet",
          "withdraw": "Withdraw",
          "no_balance": "No balance",
          "no_balance_description": "Your balance is zero now, please refill your\nwallet.",
          "add_balance": "Add balance",
          "to_account": "To account",
          "from": "From",
          "enter_amount": "Enter amount",
          "add_new_bank": "Add new bank account",
          "transaction_history": "Transaction history",
          "cardholder_name": "Cardholder name",
          "cardholder_hint": "Enter cardholder name",
          "card_number": "Card number",
          "card_number_hint": "Enter card number",
          "expire_date": "Expire date",
          "expire_date_hint": "Enter expire date",
          "cvv": "CVV",
          "cvv_hint": "Enter CVV",
          "save_card": "Save this card information",
          "general": "General",
          "my_profile": "My profile",
          "working_schedule": "Work schedules",
          "my_services": "My services",
          'price_required': 'Service price is required',
          'duration_required': 'Service duration is required',
          'buffer_time_required': 'Buffer time is required',
          'seats_required': 'Number of seats is required',
          "favorite_doctor": "Favorite doctors",
          "patient_records": "Patient records",
          "medical_records": "Medical records",
          "marketing": "Marketing",
          "change_password": "Change password",
          "change_language": "Change language",
          "select_language": "Select language",
          "more_setting": "More settings",
          "notification_setting": "Notification settings",
          "message_setting": "Message settings",
          "support": "Support",
          "privacy_policy": "Privacy and security",
          "logout": "Log out",
          "maximum_withdraw": "Maximum amount can be withdrawn",
          "how_many_withdraw": "How many do you want to withdraw?",
          "withdraw_to_bank": "Withdraw to bank account",

          //patient records
          "patient_records_title": "Patient records",
          "patient_records_favorite": "Favorite patients",
          "patient_empty": "You don't have any patient records",
          "favorite_patient": "Favorite Patients",
          "profile_detail": "Profile details",
          "records": "Records",

          //change password
          "change_password_title": "Change password",
          "current_password": "Current password",
          "new_password": "New password",
          "confirm_new_password": "Confirm new password",
          "confirm_password_hint": "Confirm your password",
          "reset_password_btn": "Reset password",

          //work schedule
          "work_schedule_title": "Work schedules",
          "all_day": "All day",
          "add_time": "Add time",

          //my services
          "my_services_title": "My services",
          "price": "Price",
          "active": "Active",
          "disable": "Disable",
          "amount": "Amount",
          "no_of_seats": "No. of seats",
          "work_availability": "Work availability",
          "save_changes": "Save changes",

          //notification setting
          "system_notification": "Enable system notifications",
          "system_notification_description": "Receive notification for new messages and appointments",
          "promotion_announcement": "Promotion announcement",
          "promotion_announcement_description": "Receive the earliest notifications about promotions and discounts",
          "sms_notification": "SMS notifications",
          "sms_notification_description": "Enable/Disable pop-up or banner notifications when in the app",
          "push_notification": "Push notifications",
          "push_notification_description": "Allow notifications only from specific categories (e.g., promotions, updates, reminders)",

          //message setting
          "message_delivery": "Message delivery",
          "message_delivery_description": "Auto-delete messages after a set time (e.g., 24 hours for certain chats)",
          "message_appearance": "Message appearance",
          "message_appearance_description": "Customize the appearance of the message screen (e.g., theme, chat bubbles)",
          "message_privacy": "Message privacy",
          "message_privacy_description": "Block or filter messages from unknown senders.",
          "message_backup": "Message backup",
          "message_backup_description": "Enable/Disable cloud backup for message history.",

          //logout screen
          "logout_confirm": "Are you sure you want to logout of this account?",
          "logout_description": "That’s sound sad to say goodbye. See you again in the next time.",
          "keep_stay": "Keep stay",
          "logout_btn": "Logout",

          //profile screen
          "profile": "My profile",
          "testimonials": "Testimonials",
          "service": "Services",
          "introduce": "Introduce",
          "schedule": "Schedule",
          "unavailable": "Unavailable",
          "available": "Available",
          "rating": "Rating",
          "view_all_review": "View all reviews",
          "edit_profile": "Edit profile",

          //edit profile screen
          "full_name_hint_long": "Enter your full name",
          "full_name_hint_long_2": "Enter your name",
          "full_name_label_long": "Full name",
          "full_name_label_long_2": "Name",
          "profession_label": "Enter your profession No.",
          "profession_hint": "Profession No.",
          "introduce_hint": "Enter your introduce",
          "medical_category": "Medical category",
          "office_address_label": "Office address",
          "office_address_hint": "Enter your office address",
          "GPS_label": "GPS",
          "GPS_hint": "Enter your latitude, Longitude",
          "company_name_label": "Company - Institution",
          "company_name_hint": "Enter your company - institution",

          //feedback screen
          "feedback": "Feedback",
          "no_feedback": "No feedback",

          //notification screen
          "notification": "Notifications",
          "all_notification": "All notifications", 
          "no_notification": "No notifications",
          "no_notification_description": "You have no new notifications yet.",
          "detail": "Detail",
          "has_made_an_appointment": "has made an appointment",
          "canceled_your_appointment": "canceled your appointment",

          //search screen
          "what_are_you_looking_for": "What're you looking for?",
          "suggest_main": "Suggested main sections",
          "browse_doctors_nearby": "Browse doctors nearby",
          "browse_hospitals_nearby": "Browse hospitals nearby",
          "browse_pharmacy_nearby": "Browse pharmacies nearby",
          "emergency_lines": "Emergency lines",
          "popular": "Popular",
          "price_from": "Price from",
          "book_appointment": "Book appointment",
          "busy": "Busy",
          "opening": "Opening",
          "closed": "Closed",
          "view_direction": "View direction",
          "available_time": "Available time",
          "all_schedules_available": "All schedules available",

          //booking screen
          "choose_services": "Choose services",
          "choose_time": "Choose time",
          "another_person": "Another person",
          "country": "Country",
          "state": "State",
          "city": "City",
          "zip_code": "Zip code",
          "summarize_medical": "Summarize your medical problem",
          "enter_history": "Enter your history medical",
          "note": "Note",
          "add_voice": "Add voice",
          "attach_file": "Attach file",
          "review_schedule": "Review schedule",
          "time&date": "Time & Date",
          "gps_location": "GPS location",
          "payment_method": "Payment method",
          "add_new_card": "Add new card",
          "choose_a_method": "Choose a method",
          "no_card": "Haven't added any card yet",
          "choose_your_payment": "Choose your payment method",
          "confirm_payment": "Confirm payment",
          "swipe_to_pay": "Swipe to pay",
          "booking_success": "Thanks, your appointment has been booked successfully!",
          "booking_success_description": "Please check your appointment history for receipt and booking details.",
          "call": "Call",
          "see_all_detail": "See all detail",
          "back_to_home": "Back to home",
          "booked_success": "Booked successfully",

          //common
          "yes": "Yes",
          "no": "No",
          "home_visit": "Home visit",
          "completed": "Completed",
          "filter": "Filter",
          "location": "Location",
          "contact": "Contact",
          "language": "Language",
          "insurance": "Insurance",
          "information": "Information",
          "empty": "Empty",
          "enter": "Enter",
          "submit": "Submit",
          "save": "Save",
          "description": "Description",
          "rejected": "Rejected",
          "reject": "Reject",
          "cancelled": "Cancelled",
          "date": "Date",
          "time": "Time",
          "address": "Address",
          "cancel": "Cancel",
          "search": "Search...",
          "search_2": "Search",
          "skip": "Skip",
          "check": "Check",
          "enter_number": "Enter number",
          "number": "Number",
          "continue_btn": "Continue",
          "attach_photo_btn": "Attach Photo",
          "complete_btn": "Complete",
          "ok_btn": "OK got it",
          "app_name": "DoctaMobile",
          "email_label": "Email",
          "email_hint": "Enter your email",
          "email_error_blank": "Email is cannot be blank",
          "email_error_invalid": "Email is invalid",
          "password_label": "Password",
          "password_hint": "Enter your password",
          "password_error_blank": "Password is cannot be blank",
          "password_error_invalid": "Password is invalid",
          "password_strength": "Password should have at least 8 characters, include of 6 alphabets, 1 number and 1 special character (&, \$, #, %).",
          "and": "and ",
          "im": "I'm ",
          "choose": "Choose",
          "problem_description": "Problem description",
          "upload": "Upload",
          "typing": "Typing...",
          "send": "Send",
          "add": "Add",

          "full_name_label": "Full Name",
          "full_name_hint": "Your full name",
          "full_name_error": "Full name cannot be blank",
          "age_label": "Age",
          "gender_label": "Gender",
          "gender_option_1": "Male",
          "gender_option_2": "Female",
          "gender_option_3": "Other",
          "height_label": "Height",
          "weight_label": "Weight",
          "blood_group_label": "Blood group",
          "medical_history_label": "Medical history",
          "medical_history_hint": "Enter your history medical",
          "medical_history_error": "Medical history cannot be blank",
          "insurance_type_label": "Insurance type",
          "insurance_type_option_1": "Public insurance",
          "insurance_type_option_2": "Private insurance",
          "public_insurance": "Public insurance",
          "private_insurance": "Private insurance",
          "insurance_error": "Insurance number cannot be blank",
          "assurances_type": "Assurances type",
          "assurances_type_option_1": "Life Insurance (Basic)",
          "assurances_type_option_2": "Life Insurance (Premium)",
          "assurances_type_option_3": "Togo Medicare C12 (Basic)",
          "assurances_type_option_4": "Togo Medicare B18 (Premium)",
          "assurances_type_option_5": "Senior Health Insur Plan A1",
          "assurances_type_option_6": "Senior Health Insur Plan B2",
          "main_insured": "Main insured",
          "main_insured_error": "Main insured cannot be blank",
          "entitled_insured": "Entitled insured",
          "entitled_insured_error": "Entitled insured cannot be blank",
          "address_label": "Address",
          "address_hint": "Enter",
          "address_error": "Address cannot be blank",
        },
      };
}
